config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  delete 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  resources :books
  resources :users, only: [:create]
  resources :sessions, only: [:create]
  root to: 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_one_attached :cover
  paginates_per 6
  belongs_to :user
  validates :name, presence: true, length: { minimum: 4 }
  validates :annotation, presence: true, length: { minimum: 10 }
  validates :authors, presence: true
  validates :user, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :password

  before_save :encrypt_password
  validates :password, presence: true, on: :create, confirmation: true, length: { minimum: 6 }
  validates :email, uniqueness: true, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.authenticate(email, password)
    user = find_by_email(email)
    user if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  end

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :ensure_logged

  def ensure_logged
    return unless current_user

    respond_to do |format|
      format.html { redirect_to books_url, notice: t('flash.session.already_logged') }
    end
  end

  helper_method :require_login

  def require_login
    return if current_user

    respond_to do |format|
      format.html { redirect_to log_in_path, alert: t('flash.session.login_required') }
      format.json { head :no_content, status: 401 }
    end
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :require_login
  before_action :check_book_access, only: %i[show edit update destroy]

  # GET /books or /books.json
  def index
    @books = Book.where(user: current_user).page(params[:page])
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: t('books.created') }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: t('books.updated') }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: t('books.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:name, :authors, :annotation, :cover)
  end

  def check_book_access
    return if @book.user.id == current_user.id

    respond_to do |format|
      format.html { redirect_to books_url, alert: t('flash.session.forbidden') }
      format.json { head :no_content, status: 403 }
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :ensure_logged, only: %i[create new]
  def new; end

  def create
    user = User.authenticate(params[:email], params[:password])
    respond_to do |format|
      if user
        session[:user_id] = user.id
        format.html { redirect_to books_url, notice: t('flash.session.logged') }
      else
        format.html { redirect_to log_in_path, alert: t('flash.session.incorrect_credentionals') }
      end
    end
  end

  def destroy
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to log_in_url, notice: t('flash.session.logged_out') }
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :ensure_logged

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to log_in_url, notice: t('flash.session.signed') }
        format.json { head :no_content, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/books/_form.html.erb
<div class="card-body text-center">
    <%= form_with(model: book) do |form| %>
        <% if book.errors.any? %>
            <div id="error_explanation">
                <ul class="list-group mb-2">
                    <% book.errors.each do |error| %>
                        <li class="list-group-item list-group-item-danger">
                            <%= error.full_message %>
                        </li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <div class="form-group">
            <div class="field">
                <%= form.label :name %>
                <%= form.text_field :name, class: "form-control" %>
            </div>

            <div class="field">
                <%= form.label :authors %>
                <%= form.text_field :authors, class: "form-control" %>
            </div>

            <div class="field">
                <%= form.label :annotation %>
                <%= form.text_area :annotation, rows: "3", class: "form-control" %>
            </div>

            <div class="field">
                <%= form.label :cover, class: "form-label" %>
                <%= form.file_field :cover, class: "form-control" %>
            </div>

            <div class="actions">
                <%= form.submit class: "btn btn-primary w-100 mt-2" %>
            </div>
        </div>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="card w-75 mx-auto rounded">
    <h1 class="card-title text-center border-bottom mb-4 pb-2 bg-secondary rounded-top"><%=  link_to t('books.editing'), @book, class: "text-white" %></h1>
    <%= render 'form', book: @book %>
</div>

app/views/books/index.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="card-title text-center border-bottom mb-4 pb-2"><%=  t('books.index') %></h1>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            <% if @books.empty? %>
                <div class="card mx-auto">
                    <h2 class="card-title text-center mb-2"><%= t("books.empty") %></h2>
                    <div>
                        <%= link_to t("books.add"), new_book_path, class: "btn btn-primary w-100" %>
                    </div>
                </div>
            <% else %>
                <% @books.each do |book| %>
                    <div class="col">
                        <div class="card">
                            <% if book.cover.attached? %>
                                <%= image_tag(book.cover,
                                              class: "card-img-top",
                                              width: 100,
                                              height: 400) %>
                            <% else %>
                                <%= image_tag(image_path("cover_missing.png"),
                                              class: "card-img-top",
                                              width: 100,
                                              height: 400) %>
                            <% end %>
                            <div class="card-body">
                                <h6 class="card-title text-center"><%= book.name %></h6>
                                <div class="btn-group w-100" role="group" aria-label="Books actions">

                                    <%= link_to t('books.show'), book, class: "btn btn-primary border border-dark" %>
                                    <%= link_to t('books.edit'), edit_book_path(book), class: "btn btn-success border border-dark" %>
                                    <%= link_to t('books.destroy'), book, method: :delete, data: { confirm: t('books.confirm_delete') }, class: "btn btn-danger border border-dark" %>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
        <%= paginate @books %>
    </div>
</div>

app/views/books/new.html.erb
<div class="card w-75 mx-auto rounded">
    <h1 class="card-title text-center border-bottom mb-4 pb-2 bg-secondary text-white rounded-top"><%=  t('books.creating') %></h1>
    <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<div class="bg-light p-5 rounded-lg m-3 border border-dark">
    <h1 class="display-4 text-center">
        <%= @book.name %>
    </h1>
    <hr class="my-4">
    <div class="card mb-3 border-0" style="background-color: #f8f9fa;">
        <div class="row g-3">
            <div class="col-md-4">
                <% if @book.cover.attached? %>
                    <%= image_tag(@book.cover, width: 300,
                                  height: 400) %>
                <% else %>
                    <%= image_tag(image_path("cover_missing.png"),
                                  class: "card-img-top",
                                  width: 300,
                                  height: 400) %>
                <% end %>
            </div>
            <div class="col-md-8">
                <div class="card-body p-0">
                    <h5 class="card-title">
                        <%= @book.authors %>
                    </h5>
                    <p class="card-text">
                        <%= @book.annotation %>
                    </p>
                </div>
                <%= link_to t("books.edit"), edit_book_path(@book) %> |
                <%= link_to t("books.back"), books_path %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-light bg-light border border-secondary mb-4">
      <div class="container-fluid">
          <a class="navbar-brand" href="<%= books_url %>">
              <%= image_tag("bookshelf.png", width: 40, height: 40) %><%= t("bookshelf") %></a>
          <div class="btn-group" role="group" aria-label="User actions">
          <% if current_user %>
              <button type="button" class="btn btn-outline-primary" disabled><%= current_user.email %></button>
              <%= link_to t("books.new"), new_book_path, class: "btn btn-primary" %>

              <%= link_to(t("books.index"), books_url, class: "btn btn-primary") %>

              <%= link_to(t("session.log_out"), log_out_path, method: :delete, data: {confirm: t("session.confirm")}, class: "btn btn-primary") %>

          <% else %>
              <%= link_to(t("session.sign_up"), sign_up_path, class: "btn btn-primary") %>
              <%= link_to(t("session.log_in"), log_in_path, class: "btn btn-primary") %>
          <% end %>

          <% if I18n.locale == :ru %>
              <%= link_to("en", options = {controller: controller_name, action: action_name, locale: :en}, class: "btn btn-primary text-uppercase mr-2") %>
          <% elsif I18n.locale == :en %>

              <%= link_to("ru", options = {controller: controller_name, action: action_name, locale: :ru}, class: "btn btn-primary text-uppercase mr-2") %>
          <% end %>
          </div>

          </div>
      </div>
  </nav>

  <body>
      <div class="container">
          <% if notice %>
              <div class="alert alert-success" role="alert"><%= notice %></div>
          <% end %>
          <% if alert %>
              <div class="alert alert-danger" role="alert"><%= alert %></div>
          <% end %>
          <%= yield %>
      </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="card w-50 mx-auto rounded">
    <h1 class="card-title text-center border-bottom mb-4 pb-2 bg-secondary text-white rounded-top"><%=  t('session.sign_up') %></h1>
    <div class="card-body text-center">
    <%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
      <div id="error_explanation">
          <ul class="list-group mb-2">
              <% user.errors.each do |error| %>
                  <li class="list-group-item list-group-item-danger">
                      <%= error.full_message %>
                  </li>
              <% end %>
          </ul>
      </div>
  <% end %>

  <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>


  <div class="form-group">
      <%= form.submit class: "btn btn-primary w-100 mt-2" %>
  </div>
    <% end %>
    <%= link_to(t("session.registered"), log_in_path, class: "link-primary") %>

    </div>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>